#!/bin/sh

#
# nullmailer startup script
#
# chkconfig: - 90 10
# description: Nullmailer is a replacement MTA which relays to a fixed
#              set of smart relays.
# processname: nullmailer
#

### BEGIN INIT INFO
# Provides:          nullmailer
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: relay-only mail transport agent
# Description:       Nullmailer is a replacement MTA which relays to a fixed
#                    set of smart relays.
### END INIT INFO

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=nullmailer
DESC="Nullmailer is a replacement MTA which relays to a fixed set of smart relays."
DAEMON=/usr/sbin/nullmailer-send
PIDFILE=/var/run/nullmailer.pid
DAEMONUSER=mail
DAEMONOPTS=-s

test -x $DAEMON || exit 0

. /lib/lsb/init-functions
if [ -f /etc/defaults/nullmailer ] ; then
	. /etc/defaults/nullmailer
fi

case "$1" in
  start)
	log_daemon_msg "Starting $NAME" || true
	if start-stop-daemon --status --quiet --oknodo --pidfile $PIDFILE -u $DAEMONUSER ; then
		log_end_msg 0
		exit 0
	elif start-stop-daemon --start --quiet --oknodo -m --pidfile $PIDFILE -c $DAEMONUSER -b --exec $DAEMON -- $DAEMONOPTS ; then
		log_end_msg 0
		exit 0
	else
		log_end_msg 1
		exit 1
	fi
	;;
  stop)
	log_daemon_msg "Stopping $NAME" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE -u $DAEMONUSER ; then
		log_end_msg 0
		exit 0
	else
		log_end_msg 1
		exit 1
	fi
	;;
  status)
	log_daemon_msg "Status $NAME" || true
	if start-stop-daemon --status --quiet --oknodo --pidfile $PIDFILE -u $DAEMONUSER ; then
		log_end_msg 0
		exit 0
	else
		log_end_msg 1
		exit 1
	fi
	;;
  restart|reload|force-reload)
	log_daemon_msg "Restarting $NAME" || true
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
	sleep 1
	if start-stop-daemon --start --quiet --oknodo -m --pidfile $PIDFILE -c $DAEMONUSER -b --exec $DAEMON -- $DAEMONOPTS ; then
		log_end_msg 0
		exit 0
	else
		log_end_msg 1
		exit 1
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload}"
	exit 2
esac

exit 0
